### ISSUE TITLE
Support OSX

### ISSUE THREAD

**Issue by karlicoss** [karlicoss/open-in-editor#1]
[This](https://github.com/smartystreets/goconvey/wiki/Opening-files-in-your-editor-from-the-Web-UI#osx) gives some examples, but I wonder if there is a simpler and more generic way...

I don't have a mac, so can't test anyway :(

**Comment by alexriabtsev** [comment]
I'm on macOS and would be glad to help you with development
Trying to install and getting an error:
`python3 open_in_editor.py --install --editor default`

`Traceback (most recent call last):`

  `File "open_in_editor.py", line 269, in <module>`
`    main()`
`  File "open_in_editor.py", line 263, in main`
`    install(editor=args.editor)`
 ` File "open_in_editor.py", line 121, in install`
`    check_call(['desktop-file-validate', str(pp)])`
`  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call`
`    retcode = call(*popenargs, **kwargs)`
`  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call`
`    with Popen(*popenargs, **kwargs) as p:`
`  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__`
`    self._execute_child(args, executable, preexec_fn, close_fds,`
`  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child`
`    raise child_exception_type(errno_num, err_msg, err_filename)`
`FileNotFoundError: [Errno 2] No such file or directory: 'desktop-file-validate'`

**Comment by karlicoss** [comment]
Ah yeah, this 100% expected because osx is using a slightly different mechanism.

To fix this, [`install`](https://github.com/karlicoss/open-in-editor/blob/ba4f105d8c090c0b3cec350de39c82e643f469ec/open_in_editor.py#L108) should check whether the system is linux or OSX (by checking `platform.system() == 'Darwin')`) and depending on the result, run `install_linux` and `install_osx`. 
As you can guess, `install_osx` needs to be written from scratch. I'd do it, but I don't have a mac nearby (and can't test on CI either because it doesn't have GUI).

**Comment by alexriabtsev** [comment]
which line(s) should I fix and test?

**Comment by karlicoss** [comment]
It's gonna be more than one line :) Basically you'd need a version of [this method](https://github.com/karlicoss/open-in-editor/blob/ba4f105d8c090c0b3cec350de39c82e643f469ec/open_in_editor.py#L108-L130) for OSX. If you manage to rewrite it completely so that it works with OSX, feel free to submit PR as is, I'll adjust the script so it picks the correct version.

Like I mentioned above, perhaps [this link](https://github.com/smartystreets/goconvey/wiki/Opening-files-in-your-editor-from-the-Web-UI#osx) or some googling might help.

**Comment by b1r3k** [comment]
I'm trying to run promnesia in docker on raspberry pi. I'm getting this: `/src/promnesia/src/promnesia/common.py:77: UserWarning: No xdg-mime on your OS! If you're on OSX, perhaps you can help me! https://github.com/karlicoss/open-in-editor/issues/1` xdg-mime is available in xdg-utils package but that has whole bunch of X-like dependencies. Will indexer work without that package?

**Comment by karlicoss** [comment]
Hey @b1r3k yeah, it's just a warning, indexer will totally work! I guess I could detect if X is available and if it's not then omit the warning altogether.
The only thing that won't work is that clicking on a link to the file in the sidebar won't open the text editor directly (because the server in Docker can't open GUI apps, at least without some nasty hacks). But even that can work if the open-in-editor script is installed on the host system.

**Comment by telotortium** [comment]
On macOS, perhaps https://github.com/Lord-Kamina/SwiftDefaultApps will help? For example, I have set up an app at work named "Lark" to open "lark:" URLs using `swda setHandler --URL lark --app /Applications/Lark.app`. You can in turn create an App from a command-line script on macOS using https://sveinbjorn.org/platypus.

**Comment by telotortium** [comment]
I've hacked together a prototype that should allow this script to work on macOS.

1. Create a file somewhere called `open-in-editor` (I put it in my home directory at `/Users/bytedance/bin/open-in-editor`) and put the following contents inside:

```
#!/usr/bin/env bash -l

# These 2 lines are useful for debugging - you can remove them later once you've debugged the script.
exec &>/tmp/open-in-editor.log
set -xv

python3 ~/misc/build/open-in-editor/open_in_editor.py --editor=emacs "$@"
rv=$?
sleep 1
ps -ef | grep '/Open In Editor$' | awk '{print $2}' | xargs kill
exit $rv
```

You should change the path `~/misc/build/open-in-editor/open_in_editor.py` to wherever `open_in_editor.py` is on your system, and change `--editor=emacs` to what you want to use. Then run `chmod +x open-in-editor` on this file to make this an executable script.

2. Download [Open In Editor.platypus.txt](https://github.com/karlicoss/open-in-editor/files/8237124/Open.In.Editor.platypus.txt), rename to `Open in Editor.platypus`.

3. Install and open [Platypus](https://sveinbjorn.org/platypus), then open the menu "Profiles > Load Profile..." and select the `Open In Editor.platypus` you just downloaded. Adjust paths to your script if necessary and then "Save Profile" to save the changes - saving the profile is the only way to edit this application if you need to fix a setting. Then click "Create App" and save it in your /Applications folder.

  You shouldn't need to change any of the other Platypus settings. In particular, you must leave "Remain running after execution" checked - this is why I kill all running `Open In Editor` processes in the `open-in-editor` script, so that you can launch the app again.

This should be all you need to get started. Let me know if you need some clarification on the instructions.

**Comment by karlicoss** [comment]
Oh wow, that's elaborate, thanks!

**Comment by mediapathic** [comment]
I am on a mac. I followed the (holy crap convoluted, but not complaining) instructions from @telotortium above. It seems to have worked insofar as it created the app named "Open in Editor.app", but when clicking on a link to edit, it's still trying to open it in the browser (it opens a new browser tab with the address `editor:///Users/mediapathic....` etc). I suspect this is an issue with the browser plugin and not the process above, but I'm putting it here just in case. 

Also @telotortium I note that when I run the created app just by clicking on it, I get the os asking me permissions to access the folder where both `open_in_editor.py` and `Open.in.Editor.platypus` are stored, twice, and it happens every time I open the app. I am certain this is not the cause of the trouble I'm having, but I strongly suspect it will be the cause of more trouble in the future should I get that far. For the record I'm running MacOS 15.5, which I assume is the problem. Just an FYI in case you still want to pursue this.
